/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaCliente.java
 */
package java2.arquivos;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author fabricio@utfpr.edu.br
 */
public class JanelaCliente extends javax.swing.JFrame {

    private Cliente cliente = null;
    private List<Cliente> clientes = null;
    private ClienteSerializer clienteSerializer = null;

    /** Creates new form JanelaCliente */
    public JanelaCliente() {
        clienteSerializer = new ClienteSerializer();
        initComponents();
    }
    
    private static int position = 0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnNovo = new javax.swing.JButton();
        jBtnFechar = new javax.swing.JButton();
        jTFNome = new javax.swing.JTextField();
        jTFFone = new javax.swing.JTextField();
        jSIdade = new javax.swing.JSpinner();
        jBtnGravar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jBtnAnterior = new javax.swing.JButton();
        jBtnProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Fone:");

        jLabel3.setText("Idade:");

        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnFechar.setText("Fechar");
        jBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFecharActionPerformed(evt);
            }
        });

        jBtnGravar.setText("Gravar");
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });
        
        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jBtnEditarActionPerformed(evt);
            }
        });
        
        jBtnRemover.setText("Remover");
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jBtnRemoverActionPerformed(evt);
            }
        });
        
        jBtnAnterior.setText("Anterior");
        jBtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jBtnAnteriorActionPerformed(evt);
            }
        });
        
        jBtnProximo.setText("Proximo");
        jBtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProximoActionPerformed(evt);
            }
        });

        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNome, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jSIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFFone)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnProximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnFechar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNovo)
                    .addComponent(jBtnGravar)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnRemover)
                    .addComponent(jBtnAnterior)
                    .addComponent(jBtnProximo)
                    .addComponent(jBtnFechar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-245)/2, 650, 245);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {
		clientes.remove(position);
		if(!clientes.isEmpty()) {
			clienteSerializer.gravarClientes(clientes);
			JOptionPane.showMessageDialog(null, "Registro excluido com sucesso", "Excluir Registro", JOptionPane.INFORMATION_MESSAGE);
		}
		this.limparTela();
	}

	private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        limparTela();
        jTFNome.requestFocus();
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFecharActionPerformed
        if(clienteSerializer != null) {
        	clienteSerializer.fecharArquivo();
        }
        System.exit(0);
    }//GEN-LAST:event_jBtnFecharActionPerformed

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        cliente = new Cliente(jTFNome.getText(), jTFFone.getText(), (Integer) jSIdade.getValue());
        if(clientes == null) {
        	clientes = new ArrayList<>();
        }
        clientes.add(cliente);
        clienteSerializer.gravarClientes(clientes);
        JOptionPane.showMessageDialog(null, "Registro gravado com sucesso", "Gravar Registro", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBtnGravarActionPerformed
    
    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {
		cliente = this.clientes.get(position);
		cliente.setNome(jTFNome.getText());
		cliente.setIdade((Integer) jSIdade.getValue());
		cliente.setFone(jTFFone.getText());
		
		if(clientes == null) {
			clientes = new ArrayList<>();
		}
		
		clientes.set(position, cliente);
		
		clienteSerializer.gravarClientes(clientes);
		JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso", "Atualizar Registro", JOptionPane.INFORMATION_MESSAGE);
	}

    private void jBtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {
    	this.lerRegistros();
    	if(position >= clientes.size()) {
    		position = clientes.size() - 1;
    	}
    	if(position > 0) {
    		position--;
    		cliente = clientes.get(position);
    	}
    	cliente = clientes.get(position);
    	atualizarTela();
	}
    
    private void jBtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProximoActionPerformed
        this.lerRegistros();
    	if(position < clientes.size() - 1) {
    		position++;
    		cliente = clientes.get(position);    		
    	}
        atualizarTela();
    }//GEN-LAST:event_jBtnProximoActionPerformed
    
    private void lerRegistros() {
    	if (clientes == null) {
        	clientes = clienteSerializer.lerRegistros();
        }
    }

    public void limparTela() {
        jTFNome.setText("");
        jTFFone.setText("");
        jSIdade.setValue((Integer) 18);
    }

    public void atualizarTela() {
        if (cliente != null && cliente.getNome() != null) {
            jTFNome.setText(cliente.getNome());
            jTFFone.setText(cliente.getFone());
            jSIdade.setValue((Integer) cliente.getIdade());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JButton jBtnAnterior;
    private javax.swing.JButton jBtnProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSIdade;
    private javax.swing.JTextField jTFFone;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
